- 数组不同于列表， 只能储存相同数据类型的值

In [8]:
from array import *

my_array = array('i', [1,2,3,4])
print(my_array)
print(my_array[1])

# i 时数组的名字

array('i', [1, 2, 3, 4])
2


## 数组的一些方法

In [19]:
## 添加
my_array = array('i', [1,2,3,4])
my_array.append(6)
print(my_array)

## 插入值， insert
my_array.insert(0, 0)
print(my_array)

## 扩展 extend
my_array_2 = array('i', [4,5,6])
my_array.extend(my_array_2)
print(my_array)

# 将列表添加到数组中 fromlist()
my_array = array('i', [1,23,4])
lst = [4,5,6]
my_array.fromlist(lst)
print(my_array)

# 移除数组中的任意元素 remove()
my_array.remove(23)
print(my_array)

## 从数组中取任意的元素的索引 index()
print(my_array.index(5))
print(my_array)
## 反转python数组 reverse()
print(my_array.reverse())

array('i', [1, 2, 3, 4, 6])
array('i', [0, 1, 2, 3, 4, 6])
array('i', [0, 1, 2, 3, 4, 6, 4, 5, 6])
array('i', [1, 23, 4, 4, 5, 6])
array('i', [1, 4, 4, 5, 6])
3
array('i', [1, 4, 4, 5, 6])
None


In [21]:
my_array = array('i', [1,3,4])
my_array.reverse()
print(my_array)

array('i', [4, 3, 1])


In [27]:
## 获取数组的缓冲信息 buffer_info()
my_array.buffer_info()

## 返回元素出现的次数 count()
my_array = array('i', [4,5,6,66,6,6])
print(my_array.count(6))

## 将数组转换成字符串
my_char_array = array('u', ['g','e', 'k'])
print(my_char_array)
my_char_array = my_char_array.tostring()
print(my_char_array)

3
array('u', 'gek')
b'g\x00e\x00k\x00'


In [28]:
## 将数组转换成列表 tolist()
my_array = array('i', [1,23,4])
my_array.tolist()

[1, 23, 4]

## 多维数组


In [29]:
a = [[1,2,3], [4,5,6], [5,6,7]]
b = a[2]
print(a)
print(b)
b[2] = 100
print(b)
print(a)

## 共享内存

[[1, 2, 3], [4, 5, 6], [5, 6, 7]]
[5, 6, 7]
[5, 6, 100]
[[1, 2, 3], [4, 5, 6], [5, 6, 100]]


In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array(a, copy=True)
print(b)
b[1][1] = 1000
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[[   1    2    3]
 [   4 1000    6]]
[[1 2 3]
 [4 5 6]]
